"use strict";

console.log(typeof 15);
console.log(typeof "15");
console.log(typeof NaN);
console.log(typeof Infinity);
console.log(typeof -Infinity);
console.log(typeof 9999999999999n);
console.log(typeof 99n);
let name = "Панас";
console.log(typeof "Привіт");
console.log(typeof "'Привіт'");
console.log(`Привіт ${name}!`);
console.log(typeof `Привіт ${name}!`);
console.log(typeof true);
console.log(typeof false);
const bull = 5 > 3;
console.log(typeof !bull);
console.log(typeof bull);
console.log(typeof null);
let name1;
console.log(typeof name1);
console.log(typeof Symbol("ver"));
console.log(typeof Math);
console.log(typeof alert);
console.log(typeof document);
console.log(typeof this);
console.log(typeof async);
console.log(typeof defer);
console.log(typeof Promise);
console.log(typeof curry);
console.log(typeof ask);
console.log(typeof showOk);
let quadro = (a, b) => (a + b) * 2;
console.log(typeof quadro);
